// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etivysvbynyrfcsoejju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0aXZ5c3ZieW55cmZjc29lamp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjIwMjAsImV4cCI6MjA2MTkzODAyMH0.mMgnKJCOtjLI8flNQI6mR7bYEVbyEE6EhrIar8GRctE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);